In [2]:
int_number = 1
float_number = 1.0
complex_number = 1 + 2j
#後面留下幾位小數點(自動四捨五入)
round_float = round(1234.5678, 1)
str2int = int('213')
 
print(round_float)
print(str2int)

1234.6
213


In [6]:
#介紹list類型資料
number_list = [0, 1, 1, 2, 3, 5, 8]
slicing_4_a_specific_pos = number_list[3]
slicing_4_the_last_pos = number_list[-1]
slicing_4_consecutive_pos = number_list[0:3]
slicing_4_the_last_three = number_list[-3:]
print(slicing_4_a_specific_pos)
 
list_list = [[1, 2, 3], [4, 5, 6]]  # list of list
A_list = list_list[0]
A_ist_list = list_list[0:2]
A_number = list_list[0][1] #第一個代表是第幾個list，第二個代表該list的第幾個元素
print(A_list)
print(A_ist_list)
print(A_number)


2
[1, 2, 3]
[[1, 2, 3], [4, 5, 6]]
2


In [5]:
# Array and slicing
import numpy as np

number_list=[0,1,1,2,3,5,8] 
#list跟array不同，list可以包含各種類型的元素，array則只能包含同一種數據類型

#不分方向的矩陣
a = np.array([1, 2, 3]) # a vector has no direction

#有方向的1*3矩陣，才能做矩陣運算，之後要嘗試用矩陣運算的思考取代迴圈
A = np.array([[1, 2, 3]]) # a 1 x 3 array that can be transposed

##
a_T = a[:, np.newaxis] # a' although a has no direction
A_T = A.T # A的transpose矩陣 # 3*1矩陣
B = A.reshape(-1, 1) # 3*1矩陣
C = np.array([1, 2, 3], ndmin = 2) # convert a to A
E = A.reshape(1,-1) # 1*3矩陣

print(np.size(a))  # == print(a.size) number of elements in a
#3
print(np.shape(A_T))  # == print(A_T.shape) , array dimension
#(3,1)
 
D = np.array([[1, 2, 3],[4, 5, 6]]) #2*3矩陣
print(D[1]) # D[1] = D[1,:] # second row and all columns
#[4,5,6]
print(D[:, 1])#所有元素的第2個值
#[2,5]
print(D[:, 0:-1])#所有元素的0:-1的值
#[1,2],[4,5]
print(D[:, 1:])#所有元素從1到最後的值
#[2,3],[5,6]
print(D[:, -2:])#所有元素從-2到最後的值
#[2,3],[5,6]


3
(3, 1)
[4 5 6]
[2 5]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]


In [2]:
# vector concatenation
#矩陣合併
import numpy as np
va = np.array([1, 2, 3])
vb = np.array([4, 5, 6])
#資料單純疊加
vc = np.concatenate((va, vb), axis = 0) # flatten a, b; try axis=1
#資料單純疊加
vd = np.append(va, vb)
#水平疊加
ve = np.hstack((va, vb)) #(1,6)
#垂直疊加
vF = np.vstack((va, vb)) #(2,3)

vg = np.r_[va, vb] #[1 2 3 4 5 6]
vG = np.c_[va, vb] #[1 4] [2 5] [3 6]

vH = (va, vb) # a tuple #包含兩個array

#matrix concatenation
 
ma = np.array([[1, 2, 3]]) # 1 x 3
mb = np.array([[4, 5, 6]]) # 1 x 3
mc = np.hstack((ma, mb))   # 1 x 6
  
# Vertically, concatenate row-wisely 
mC = np.concatenate((ma, mb), axis = 0) # 2 x 3 #[[1 2 3] [4 5 6]]
mD = np.r_[ma, mb] # 2 x 3 #[[1 2 3] [4 5 6]]
mE = np.vstack((ma,mb)) #2 x 3 #[[1 2 3] [4 5 6]]
  
# Horizontally, concatenate column-wisely
mF = np.concatenate((ma.T, mb.T), axis =1) # 3 x 2 #[[1 4] [2 5] [3 6]]
#[1,4],[2,5],[3,6]
mG = np.hstack((ma.T, mb.T)) # 3 x 2
#[1,4],[2,5],[3,6]
mH = np.c_[ma.T, mb.T] # 3 x 2
#[1,4],[2,5],[3,6]

In [11]:
S = np.array([[1, 3, 2], [6, 5, 4]])#2*3矩陣
print(S)
print(S.max()) #所有元素最大值
#6
print(S.max(0)) # column max
#[6,5,4]
print(np.max(S, axis = 1)) # row max
#[3,6] #3搭配6最大
 
a = S.flatten() # turn into vector
#[1 3 2 6 5 4]
b = S.flatten('F') # turn into vector column-wise
#[1 6 3 5 2 4]

S[S < 3] = 0 # check what S looks like

print(a)
print(b)
 
c = [1, 2, 3, 4]
C = np.tile(c,(5,1)) # 5 x 4 matrix
#[[1 2 3 4]
# [1 2 3 4]
# [1 2 3 4]
# [1 2 3 4]
# [1 2 3 4]]
d = np.reshape(C, (-1, 1)) # convert to Column vector
#20*1矩陣
print(c)
print(C)
print(d)

[[1 3 2]
 [6 5 4]]
6
[6 5 4]
[3 6]
[1 3 2 6 5 4]
[1 6 3 5 2 4]
[1, 2, 3, 4]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]]


Tuple Introduction


In [12]:
a_tuple = (0, 0) # ordered sequence
also_a_tuple = 0, 0
a_3d_tuple = (0, 1, 2) # (2,1,0) is different, however the list  [0,1,2] := [1,2,0]

Special Matrix

In [14]:
import numpy as np

#建立0矩陣 #感覺可以用再用迴圈的時候
Z = np.zeros((3,4)) # 3 x 4 zero matrix
#建立全部是1的矩陣
One =  np.ones((3,4)) # 3 x 4 one matrix
#建立單位矩陣
I = np.eye(3) # 3 x 3 identity matrix
#建立對角線矩陣
D = np.diag([1, 2, 3, 4]) # a diagonal matrix
e = np.diag(I) # the diagonal of I
print(Z)
print(One)
print(I)
print(D)
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1. 1. 1.]


In [16]:
import numpy as np
  
x0 = [1, 2, 3, 4, 5, 6, 7, 8, 9] # a list
x1 = range(1, 10, 1) # a range
x2 = np.arange(1, 10, 1)  # an array of integer numbers
x3 = np.linspace(1, 9, 9)  # an array of float number
x4 = np.arange(10)  # start from 0 to 9
x5 = np.linspace(0, 100, 1000)
print(x0)
print(x1)
print(x2) #建立一個從1-9的array
#[1 2 3 4 5 6 7 8 9]
print(x3)
#[1. 2. 3. 4. 5. 6. 7. 8. 9.]
print(x4)
#[0 1 2 3 4 5 6 7 8 9]
print(x5)#0到100切1000個點
 
y1 = x2 + x3 + 1 # not x0 + x1 + 1
y2 = x2 ** 2 + x2 - 2
y3 = x2 / x3
print(y1)
print(y2)
print(y3)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
range(1, 10)
[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]
[  0.           0.1001001    0.2002002    0.3003003    0.4004004
   0.5005005    0.6006006    0.7007007    0.8008008    0.9009009
   1.001001     1.1011011    1.2012012    1.3013013    1.4014014
   1.5015015    1.6016016    1.7017017    1.8018018    1.9019019
   2.002002     2.1021021    2.2022022    2.3023023    2.4024024
   2.5025025    2.6026026    2.7027027    2.8028028    2.9029029
   3.003003     3.1031031    3.2032032    3.3033033    3.4034034
   3.5035035    3.6036036    3.7037037    3.8038038    3.9039039
   4.004004     4.1041041    4.2042042    4.3043043    4.4044044
   4.5045045    4.6046046    4.7047047    4.8048048    4.9049049
   5.00500501   5.10510511   5.20520521   5.30530531   5.40540541
   5.50550551   5.60560561   5.70570571   5.80580581   5.90590591
   6.00600601   6.10610611   6.20620621   6.30630631   6.40640641
   6.50650651   6.60660661   6.70670671 

In [11]:
#%% string & indexing
  
s1 = 'a single quote string'
s2 = "a double quote string"
s3 = '''a triple quote string'''
  
print(s3[0])#a
print(s2[:4])#a do
print(s3)
  
s4 = """
Triple double quotes
is usually used
in multiple lines, such as documents
"""
print(s4)
 
# concatenate strings
s5 = 'This is ' + s1
  
# string list
str_list = ['r', 'g', 'b', 'k', 'y']
print(str_list[1])
  
# Dictionaries
meals = {'breakfast': 'sardines', 'lunch': 'salad', 'dinner': 'cake', 'cost':40}
print(meals['breakfast'])#g
print(meals['cost'])#sardines
print('The meal costs {} dollars'.format(meals['cost'])) 
#The meal costs 40 dollars

a
a do
a triple quote string

Triple double quotes
is usually used
in multiple lines, such as documents

g
sardines
40
The meal costs 40 dollars


In [21]:
col_names = ['col1', 'col2', 'col3'] # string list
col_names_join = ','.join(col_names) # convert to a string
col_names_split = col_names_join.split(',') # convert a string to a list
print(col_names_join) 
#[col1,col2,col3]
print(col_names_split)
#["col1","col2","col3"]
 
a_sentence = "台北大學統計系"
where_am_I = a_sentence.find('統計')
where_is_it = a_sentence.find('會計') # -1 means NOT FOUND
print(where_am_I)#4
print(where_is_it)#-1

col1,col2,col3
['col1', 'col2', 'col3']
4
-1


In [27]:
from numpy import linalg #numpy裡面的套件linalg，因為套件很多，必須要加入這行，使用時才不用加很長
import numpy as np 
import scipy.linalg as LA # scipy's linear algebra is better
 
X = np.array([[1,2,3],[4,5,6]]) # a 2x3 matrix
# check the information of X
Xdim = X.ndim
Xshape = X.shape
Xsize = X.size
print(Xdim)#2
print(Xshape)#(2,3)
print(Xsize)#6 #共6個元素
 
a = X[0, 1]
P = X * X # element by element multiplication
Q = X / X # element by element division
R = X @ X.T # XX'
print(a)
#2
print(P)
#[[ 1  4  9]
# [16 25 36]]
print(Q)
#[[1. 1. 1.]
# [1. 1. 1.]]
print(R)
#[[14 32]
# [32 77]]

#total_sum=np.sum(X) #從numpy取出
total_sum = X.sum() # X.mean()... #要X是numpy物件才可以取出
row_sum = X.sum(axis = 1) # sum over each row
col_sum = X.sum(axis = 0) # sum over each column
# col_sum = np.sum(X, axis = 0) 
print(total_sum)#21
print(row_sum)#[ 6 15]
print(col_sum)#[5 7 9]
 
A = np.array([[1, 1, 1],[2, 4, 6],[5, 7, 6]])
b = np.array([1, 2, 3])
x =  LA.inv(A) @ b  # Ax = b
xsol = LA.solve(A, b) # Ax = b
I = A @ LA.inv(A) # double check what LA.inv(A) is
print(A)
#[[1 1 1]
# [2 4 6]
# [5 7 6]]
print(b)
#[1 2 3]
print(x)
#[ 1.66666667 -1.33333333  0.66666667]
print(xsol)
#[ 1.66666667 -1.33333333  0.66666667]
print(I)
#[[ 1.00000000e+00  1.66533454e-16 -1.66533454e-16]
# [ 4.44089210e-16  1.00000000e+00 -6.66133815e-16]
# [ 2.22044605e-15  7.77156117e-16  1.00000000e+00]]

 
A_square = linalg.matrix_power(A, 2) # nth power of a matrix
A_square_root = LA.fractional_matrix_power(A, 0.5)
print(A_square)
#[[ 8 12 13]
# [40 60 62]
# [49 75 83]]
print(A_square_root)
#[[0.73878486-0.02707346j 0.24860816-0.02513898j 0.24396951+0.0236736j ]
# [0.42299787+0.73072319j 1.41039089+0.67851076j 1.53803548-0.63895957j]
# [1.29406597-0.66263317j 1.78200499-0.61528598j 1.91224586+0.57942024j]]
 
B = np.vstack((A, b)) # 4 x 3
C = np.hstack((A, b.reshape(3, 1))) # 3 x 4
print(B)
#[[1 1 1]
# [2 4 6]
# [5 7 6]
# [1 2 3]]
print(C)
#[[1 1 1 1]
# [2 4 6 2]
# [5 7 6 3]]
 
B_row = np.insert(A, 3, b, 0) # 3 is the position index; 0 is for row
B_col = np.insert(A, 3, b, 1) # 3 is the position index; 1 is for column
print(B_row)
#[[1 1 1]
# [2 4 6]
# [5 7 6]
# [1 2 3]]
print(B_col)
#[[1 1 1 1]
# [2 4 6 2]
# [5 7 6 3]]

[[ 8 12 13]
 [40 60 62]
 [49 75 83]]
[[0.73878486-0.02707346j 0.24860816-0.02513898j 0.24396951+0.0236736j ]
 [0.42299787+0.73072319j 1.41039089+0.67851076j 1.53803548-0.63895957j]
 [1.29406597-0.66263317j 1.78200499-0.61528598j 1.91224586+0.57942024j]]
[[1 1 1]
 [2 4 6]
 [5 7 6]
 [1 2 3]]
[[1 1 1 1]
 [2 4 6 2]
 [5 7 6 3]]
[[1 1 1]
 [2 4 6]
 [5 7 6]
 [1 2 3]]
[[1 1 1 1]
 [2 4 6 2]
 [5 7 6 3]]


In [33]:
import numpy as np 
  
x = np.array([1, 2, 5, 3, 2])
x[x > 3] = 9 # replaced by 9; conditioned on x>3
y = np.where(x > 3, 9, x)
z = np.where(x >=3, 1, 0)
#-------------------------------
p = [] # p is a empty list
print(not p)  # check if p is empty or not
# print(p is None) 
# Check whether variable p is defined or not
print('p' in locals())
#-------------------------------
a = 3
if a > 1 and a < 5 :
    print('TRUE')
else :
    print('FALSE')
  
if a > 5 or a < 1 :
    print('OUTSIDE')
else :
    print('INSIDE')
#-------------------------------
# compact expression for if...else...
flag = 1
status = "play" if flag ==1 else "stop"
print(status)

True
True
TRUE
INSIDE
play


In [41]:
import pandas as pd
 
A = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
df = pd.DataFrame(A)
df

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [42]:
df.columns = ["col1", "col2", "col3", "col4"]
c1 = [91, 92, 93]
c2 = [71, 72, 73]
c3 = [51, 52, 53]
c4 = [31, 32, 33]
df = df.assign(col5 = c1) # add c1 to the last column with header="col5"
df.insert(2, 'new', c2) # insert c2 to column#2 with header="new"
df['col6'] = c3 # add c3 to the last column with header="col6"
df

col1  col2  new  col3  col4  col5  col6
0     1     2   71     3     4    91    51
1     5     6   72     7     8    92    52
2     9    10   73    11    12    93    53

In [43]:
r1 = [81, 82, 83, 84, 85, 86, 87]
df.loc[len(df)] = r1 # add r1 to the last row (the last location)
r2 = [61, 62, 63, 64, 65, 66, 67]

df.loc[-0.5] = r2 # add r2 and move to the top location
df = df.sort_index().reset_index(drop=True) 

df.loc[1.5] = r2 # insert r2 in the location between row1 and row2
df = df.sort_index().reset_index(drop=True)
df

col1  col2  new  col3  col4  col5  col6
0    61    62   63    64    65    66    67
1     1     2   71     3     4    91    51
2    61    62   63    64    65    66    67
3     5     6   72     7     8    92    52
4     9    10   73    11    12    93    53
5    81    82   83    84    85    86    87

In [44]:
# 察看結果便知道下列幾行的功能
df.drop(['new', 'col6'], axis=1, inplace=True)#把new,col6刪掉
df.drop(df.index[2], inplace=True)#刪掉第二個row
df = df.sort_index().reset_index(drop=True)
df

col1  col2  col3  col4  col5
0    61    62    64    65    66
1     1     2     3     4    91
2     5     6     7     8    92
3     9    10    11    12    93
4    81    82    84    85    86

In [20]:
print(df.loc[0:3]) # loc denotes row number
print(df[["col2", "col3"]].loc[0:2])
print(df.iloc[0:3, 0:4])#row取0,1,2 #column取0,1,2,3

D = df.values.astype(int) # convert pandas dataframe to numpy array
print(D)

   col1  col2  col3  col4  col5
0    61    62    64    65    66
1     1     2     3     4    91
2     5     6     7     8    92
3     9    10    11    12    93
   col2  col3
0    62    64
1     2     3
2     6     7
   col1  col2  col3  col4
0    61    62    64    65
1     1     2     3     4
2     5     6     7     8
[[61 62 64 65 66]
 [ 1  2  3  4 91]
 [ 5  6  7  8 92]
 [ 9 10 11 12 93]
 [81 82 84 85 86]]


In [22]:
import pandas as pd
 
penguins_data="https://raw.githubusercontent.com/datavizpyr/data/master/palmer_penguin_species.tsv"
df = pd.read_csv(penguins_data, sep="\t")  # pd.read_excel()
df = df.dropna() # drop NA data (missing data)
print(df.head(10)) # print out the first 10 rows of data
print(df.info())
print(df.describe())
df.to_excel('pengnus_species.xlsx') # save as a xlsx file


   species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0   Adelie  Torgersen              39.1             18.7              181.0   
1   Adelie  Torgersen              39.5             17.4              186.0   
2   Adelie  Torgersen              40.3             18.0              195.0   
4   Adelie  Torgersen              36.7             19.3              193.0   
5   Adelie  Torgersen              39.3             20.6              190.0   
6   Adelie  Torgersen              38.9             17.8              181.0   
7   Adelie  Torgersen              39.2             19.6              195.0   
12  Adelie  Torgersen              41.1             17.6              182.0   
13  Adelie  Torgersen              38.6             21.2              191.0   
14  Adelie  Torgersen              34.6             21.1              198.0   

    body_mass_g     sex  
0        3750.0    MALE  
1        3800.0  FEMALE  
2        3250.0  FEMALE  
4        3450.0  FEMALE  
